name: bilinear_CM
method: random
metric:
  name: mean_val_loss
  goal: minimize

parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  learning_rate:
    values: [0.0001, 0.0005]
  batch_size:
    values: [256, 512]
  regularization:
    values: ['l2']
  lambda_reg:
    values: [0, 0.001, 0.01, 0.1]
  epochs:
    values: [75, 100, 125]

# BEST PARAMETERS PCA AS INPUT
best_parameters:
  input_dim:
    value: !!int 0 
  binarize:
    value: !!int 0
  learning_rate:
    values: [0.0005]
  batch_size:
    values: [512]
  regularization:
    values: ['l2']
  lambda_reg:
    values: [0.01]
  epochs:
    values: [100]