method: random
metric:
  name: mean_val_loss
  goal: minimize

parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  token_encoder_dim:
    values: [20, 40]
  d_model:
    values: [64, 128, 256]
  encoder_output_dim:
    values: [10, 20]
  use_positional_encoding:
    values: [False]
  nhead:
    values: [2, 4, 8]
  num_layers:
    values: [2, 4, 6]
  deep_hidden_dims:
    values:
      - [512, 256]
  cross_attention_dropout:
    values: [0.1, 0.2]
  dropout_rate:
    values: [0.1, 0.2]
  learning_rate:
    values: [0.00009, 0.00001, 0.0001]
  weight_decay:
    values: [0, 0.0001]
  batch_size:
    values: [128, 256]
  epochs:
    values: [75, 100, 125]

best_parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  token_encoder_dim:
    values: [20]
  d_model:
    values: [128]
  encoder_output_dim:
    values: [10]
  use_positional_encoding:
    values: [False]
  nhead:
    values: [2]
  num_layers:
    values: [2]
  deep_hidden_dims:
    values:
      - [256, 128]
  transformer_dropout:
    values: [0.2]
  dropout_rate:
    values: [0.2]
  learning_rate:
    values: [0.00009]
  weight_decay:
    values: [0.0001]
  batch_size:
    values: [512]
  epochs:
    values: [20]