name: dynamic_mlp
method: random
metric:
  name: mean_val_loss
  goal: minimize

# SMALL GRID
parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  hidden_dims:
    values:
      - [128, 64]
      - [256, 128]
      - [512, 256, 128]
  learning_rate:
    values: [0.00009, 0.0001]
  batch_size:
    values: [128, 256, 512]
  dropout_rate:
    values: [0, 0.1, 0.2, 0.3]
  weight_decay:
    values: [0.0001, 0.00001, 0]
  epochs:
    values: [75, 100, 125]

# REGRESSION
best_parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  hidden_dims:
    values:     
    - [256, 128]
  learning_rate:
    values: [0.00009]
  batch_size:
    values: [512]
  dropout_rate:
    values: [0.1]
  weight_decay:
    values: [0.0001]
  epochs:
    values: [125]