name: shared_transformer
method: random
metric:
  name: mean_val_loss
  goal: minimize

parameters: 
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  token_encoder_dim:
    values: [20, 60]
  d_model:
    values: [128]
  encoder_output_dim:
    values: [10]
  use_alibi:
    values: [True, False]
  nhead:
    values: [2, 4] 
  num_layers:
    values: [2, 4]
  deep_hidden_dims:
    values:
    - [256, 128]
  transformer_dropout:
    values: [0, 0.2]
  dropout_rate:
    values: [0, 0.2]
  learning_rate:
    values: [0.00009]
  weight_decay:
    values: [0.0001]
  batch_size:
    values: [512]
  aug_prob:
    values: [0, 0.1, 0.3, 0.45]
  epochs:
    values: [50, 70]

best_parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  token_encoder_dim:
    values: [60] # 20 or 60 necessary for n head = 4 
  d_model:
    values: [128]
  encoder_output_dim:
    values: [10]
  use_alibi:
    values: [True]
  nhead:
    values: [4] 
  num_layers:
    values: [4]
  deep_hidden_dims:
    values:
    - [256, 128]
  transformer_dropout:
    values: [0.2]
  dropout_rate:
    values: [0.2]
  learning_rate:
    values: [0.00009]
  weight_decay:
    values: [0.0001]
  batch_size:
    values: [512]
  aug_prob:
      values: [0.45]
  epochs:
    values: [70]